import { Category } from "../types/category";

export const _mockCategories: Category[] = [
  {
    categoryId: "1",
    name: "Peripherals",
    slug: "peripherals",
    seoTitle: "Computer Peripherals Online",
    seoDescription:
      "Find keyboards, mice, headphones, and all computer accessories.",
    iconName: "FiHeadphones",
    image: "/images/category/peripheral.png",
    children: [
      {
        categoryId: "1-1",
        name: "Keyboards",
        slug: "keyboards",
        seoTitle: "Mechanical & Membrane Keyboards",
        seoDescription: "Buy gaming and office keyboards online.",
        iconName: "FiKeyboard",
        image: "/images/category/keyboard.png",
        parentId: "1",
      },
      {
        categoryId: "1-2",
        name: "Mice",
        slug: "mice",
        seoTitle: "Computer Mice",
        seoDescription: "Gaming, wireless, and ergonomic mice.",
        iconName: "FiMousePointer",
        image: "/images/category/mouse.png",
        parentId: "1",
      },
      {
        categoryId: "1-3",
        name: "Headphones",
        slug: "headphones",
        seoTitle: "Headphones & Earbuds",
        seoDescription: "High-quality wired and wireless headphones.",
        iconName: "FiHeadphones",
        image: "/images/category/headphones.png",
        parentId: "1",
      },
    ],
  },
  {
    categoryId: "2",
    name: "Laptops / PCs",
    slug: "laptops-pcs",
    seoTitle: "Laptops and PCs",
    seoDescription:
      "High-performance laptops and desktop computers for work and gaming.",
    iconName: "FiMonitor",
    image: "/images/category/pc.png",
    children: [
      {
        categoryId: "2-1",
        name: "Gaming Laptops",
        slug: "gaming-laptops",
        seoTitle: "High-Performance Gaming Laptops",
        seoDescription: "Top gaming laptops for an immersive experience.",
        iconName: "FiCpu",
        image: "/images/category/gaming-laptop.png",
        parentId: "2",
      },
      {
        categoryId: "2-2",
        name: "Ultrabooks",
        slug: "ultrabooks",
        seoTitle: "Slim & Lightweight Ultrabooks",
        seoDescription: "Portable laptops with long battery life.",
        iconName: "FiLaptop",
        image: "/images/category/ultrabook.png",
        parentId: "2",
      },
      {
        categoryId: "2-3",
        name: "Desktop PCs",
        slug: "desktop-pcs",
        seoTitle: "Powerful Desktop Computers",
        seoDescription:
          "Customizable and pre-built desktops for work and gaming.",
        iconName: "FiMonitor",
        image: "/images/category/desktop.png",
        parentId: "2",
      },
    ],
  },
  {
    categoryId: "3",
    name: "Smartphones",
    slug: "smartphones",
    seoTitle: "Latest Smartphones Online",
    seoDescription:
      "Explore the newest smartphones with the best prices and features.",
    iconName: "FiSmartphone",
    image: "/images/category/tel.png",
    children: [
      {
        categoryId: "3-1",
        name: "Android Phones",
        slug: "android-phones",
        seoTitle: "Top Android Smartphones",
        seoDescription:
          "Latest Android phones from Samsung, Google, Xiaomi, etc.",
        iconName: "FiSmartphone",
        image: "/images/category/android.png",
        parentId: "3",
      },
      {
        categoryId: "3-2",
        name: "iPhones",
        slug: "iphones",
        seoTitle: "Apple iPhones",
        seoDescription: "Explore the latest iPhone models.",
        iconName: "FiSmartphone",
        image: "/images/category/iphone.png",
        parentId: "3",
      },
      {
        categoryId: "3-3",
        name: "Accessories",
        slug: "smartphone-accessories",
        seoTitle: "Phone Cases, Chargers, & More",
        seoDescription: "All must-have accessories for smartphones.",
        iconName: "FiGift",
        image: "/images/category/phone-accessories.png",
        parentId: "3",
      },
    ],
  },
];
