import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/shared/layout/HeaderTop";
import HeaderWithSidebar from "@/shared/layout/HeaderWithSidebar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <HeaderTop />
        <HeaderWithSidebar />
        <main className="sm:pl-[70px] w-full">{children}</main>
      </body>
    </html>
  );
}
